openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "An API about items"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Item:
      type: "object"
      required:
        - name
        - description
        - price
        - rank
      properties:
        name:
          type: "string"
        description:
          type: "string"
        price:
          type: "number"
        rank:
          type: "integer"


paths:
  /items:
    get:
      operationId: "items.read_all"
      tags:
        - "Items"
      summary: "Read the list of items"
      responses:
        "200":
          description: "Successfully read item list"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Item"
    post:
      operationId: "items.create"
      tags:
        - "Items"
      summary: "Create an item"
      requestBody:
        x-body-name: "item"
        description: "Item to create"
        required: True
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Item"
      responses:
        "201":
          description: "Successfully created person"
        "406":
          description: "Item with that description already exists"